web:
  env_file: web.env
  build: .
  command: python app.py
  volumes:
    - .:/code
  expose:
    - "80"
  ports:
    - 5001:80
  links:
    - db
    - mailer

db:
  image: redis
  volumes:
    - /data

mailer:
  image: tozd/postfix
  expose:
    - "25"
  environment:
    - MAILNAME=stord.io
    - MY_NETWORKS=172.17.0.0/16 127.0.0.0/8
    - MY_DESTINATION=localhost.localdomain, localhost, stord.io
    - ROOT_ALIAS=admin@stord.io

caddy:
  image: abiosoft/caddy
  links:
      - web
  volumes:
    - ./Caddyfile:/etc/Caddyfile
    - /root/.caddy:/root/.caddy
  ports:
    - 80:80
    - 443:443
