web:
  env_file: web.env
  build: .
  command: python app.py
  volumes:
    - .:/code
  expose:
    - "80"
  ports:
    - "5000:80"
  links:
    - db
    - mailer

db:
  image: redis
  volumes:
    - /data

mailer:
  image: tozd/postfix
  expose:
    - "25"
  environment:
    - MAILNAME=stord.io
    - MY_NETWORKS=172.17.0.0/16 127.0.0.0/8
    - MY_DESTINATION=localhost.localdomain, localhost, stord.io
    - ROOT_ALIAS=admin@stord.io

nginx-proxy:
  image: jwilder/nginx-proxy
  ports:
    - "80:80"
  links:
    - web
  volumes:
    - /var/run/docker.sock:/tmp/docker.sock:ro